<?php
$lang = array(
	'referer_info_utm_source' => 'Источник перехода',
	'referer_info_utm_medium' => 'Средство маркетинга',
	'referer_info_utm_campaign' => 'Рекламная кампания',
	'referer_info_utm_content' => 'Объявление',
	'referer_info_utm_partner' => 'Партнер',
	'referer_info_utm_term' => 'Ключевые слова',
	'referer_info_source_type' => 'Тип площадки',
	'referer_info_source' => 'Площадка',
	'referer_info_position_type' => 'Позиция',
	'referer_info_position' => 'Номер позиции',
	'referer_info_keyword' => 'Запрос',
	'referer_info_referer' => 'Ссылка',
	'setting_password' => 'Пароль',
	'setting_qtsms_host' => 'Сервер QTelecom',
	'setting_qtsms_login' => 'Логин QTelecom',
	'setting_qtsms_password' => 'Пароль QTelecom',
	'setting_qtsms_phone' => 'Телефон',
	'setting_qtsms_sender' => 'Отправитель',
	'setting_admin_email' => 'E-Mail администратора',
	'setting_timer' => 'Время приема заявок',
	'setting_email_subject' => 'Тема письма',
	'setting_email_message' => 'Текст письма',
	'setting_reviews_quantity' => 'Кол-во отзывов',
	'setting_review_update_date' => 'Дата последнего обновления отзывов',
	'setting_bitrix_login' => 'Логин в Bitrix24',
	'setting_bitrix_password' => 'Пароль в Bitrix24',
	'setting_bitrix_url' => 'Адрес в Bitrix24',
	'setting_timer_date' => 'Дата окончания набора',
	'setting_phone_message' => 'Текст смс',
	'setting_open_door' => 'День открытых дверей',

	'menu_main' => 'Панель упраления',
	'menu_orders' => 'Заказы',
	'menu_shares' => 'Акции',
	'menu_subscribes' => 'Продукты',
	'menu_ab_tests' => 'A / B тесты',
	'menu_utm' => 'UTM контент',
	'menu_settings' => 'Настройки',
	'menu_reviews' => 'Отзывы',
	'menu_templates' => 'Шаблоны',
	'menu_code_editor' => 'Редактор кода'
);
?>